### PR TITLE
Re #2127: make crosshair linked views rotations around the focus of the crosshair

### PR DESCRIPTION
**Pull request by Punzo**
Solve the rotation of the linked views as suggested in https://github.com/OHIF/Viewers/issues/2127

### CODE REVIEW

**Comment by Punzo** [comment]
@andrebot @igoroctaviano when you have time, cane you please review? thanks!

**Comment by igoroctaviano** [comment]
> Solve the rotation of the linked views as suggested in [OHIF/Viewers#2127](https://github.com/OHIF/Viewers/issues/2127)

Hey @Punzo can you share the steps to test the change? that would be great.

**Comment by Punzo** [comment]
@igoroctaviano you can start the examples and you get the MPR Rotatable Crosshairs Example.

Then you pan the views and move the crosshair in the middle green slice, something like this:
image


After rotation (middle view, green slice) without fix:



After rotation (middle view, green slice) with fix:
image

**Comment by Punzo** [comment]
@igoroctaviano I have actually found that with https://github.com/OHIF/react-vtkjs-viewport/pull/123/commits/3c8b9becf989ca792ec87e96bc4fe183b826e8d5 introduce some bugs in the crosshair translation update after the rotation. I'll find a fix and update you when I have done.

**Comment by Punzo** [comment]
> @igoroctaviano I have actually found that with [3c8b9be](https://github.com/OHIF/react-vtkjs-viewport/commit/3c8b9becf989ca792ec87e96bc4fe183b826e8d5) introduce some bugs in the crosshair translation update in the linked views after the rotation. I'll find a fix and update you when I have done.

@igoroctaviano fixed in https://github.com/OHIF/react-vtkjs-viewport/pull/123/commits/b95fe313b6de45c0865282e8d136de89eb99cc36

**Comment by jmargeta** [comment]
@Punzo, this is a great PR. The panning works correctly now, thank you.

After rotation, the displacement of the cursor seems to be causing a slight drift (the most visible on the image in the middle of the animation below).
drift

It seems that the displacement is along the axis perpendicular to the plane. I would expect that the manipulated view stays the same on movement of the cross-hair and that only the two other views would change.

I am on the latest commit of this PR.

**Comment by Punzo** [comment]
> @Punzo, this is a great PR. The panning works correctly now, thank you.
> 
> After rotation, the displacement of the cursor seems to be causing a slight drift (the most visible on the image in the middle of the animation below).
> drift
> 
> It seems that the displacement is along the axis perpendicular to the plane. I would expect that the manipulated view stays the same on movement of the cross-hair and that only the two other views would change.
> 
> I am on the latest commit of this PR.

thanks for testing @jmargeta. I could reproduce as well. There is indeed a shift of the crosshair along the line of sight of the camera when panning after a rotation. I am not sure why, I am working on it.

**Comment by Punzo** [comment]
https://github.com/OHIF/react-vtkjs-viewport/pull/123/commits/210bb044d14764ba0b90631d7343966b2d0d1546 fix https://github.com/OHIF/react-vtkjs-viewport/pull/123#issuecomment-726595902. @jmargeta @igoroctaviano please test and review when you have time. Thanks!

**Review by igoroctaviano — APPROVED** [review]
Tested locally, LGTM. 

Screen Shot 2020-11-13 at 07 22 32

**Comment by jmargeta** [comment]
Thanks @Punzo, for your quick fix! I tested and can confirm that this works beautifully

**Pull request merged**
