### PR TITLE
feat(View2D): Show paint widget cursor in MPR

### PR DESCRIPTION
**Pull request by floryst**
Show paint widget cursor when painting in MPR view.

### CODE REVIEW

**Comment by swederik** [comment]
Thanks!

**Comment by LaurentTrk** [comment]
Hi guys,
Using the 0.9.0 version, I don't see the paint widget cursor in my view, nor in the online example (https://react-vtkjs-viewport.netlify.app/painting).
Did I miss something ?

**Comment by LaurentTrk** [comment]
Hi @dannyrb , thanks for your quick reply !
By cursor, I mean this one : https://kitware.github.io/vtk-js/examples/PaintWidget.html
With a circle showing the area to be paint

**Comment by dannyrb** [comment]
If you squint _reaaallllyyy_ hard, you can see a blue circle when hovering in the black edges of the viewport on the right. My guess is that the radius/scale we're using is very, very tiny.

**Comment by LaurentTrk** [comment]
Woww ! Perfect, thanks for the help

**Comment by LaurentTrk** [comment]
Hi @dannyrb ,
Did you also notice that the painting of the blue circle is not correct when zooming ?
It seems that the zoom factor is not applied to the paint widget.
Any tips to fix this ? Thanks for your help :)

**Pull request merged**
